/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "HostedZone": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KofiUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PsswdWeb": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}