name: Deploy Psswd
on:
  push:
    branches:
      - "actions-testing"
  # release:
  #     types:
  #       - released
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-duration-seconds: 1200
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
      - name: get caller identity
        run: |
          echo stage: '${{ vars.STAGE }}' | KOFI_USER: ${{ vars.KOFI_USER }} | HOSTED_ZONE: ${{ vars.HOSTED_ZONE }} | DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      # - name: Deploy with SST
      #   run: yarn sst deploy --stage ${{ vars.STAGE }}
      #   env:
      #     KOFI_USER: ${{ vars.KOFI_USER }}
      #     HOSTED_ZONE: ${{ vars.HOSTED_ZONE }}
      #     DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
